# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import GUI.first
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog, QWidget, QMainWindow


class Ui_MainWindow(QWidget):
    filepath="null"
    ship_name="ship name"
    ship_type="ship type"
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 120, 111, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 190, 111, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 260, 111, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(380, 50, 161, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(380, 130, 161, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 70, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 150, 54, 12))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_4.clicked.connect(self.exit_application)
        self.pushButton.clicked.connect(self.openFolderDialog)
        self.pushButton_2.clicked.connect(self.comfirm)
        self.pushButton_3.clicked.connect(self.destory_filepath)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def exit_application(self):
        QApplication.instance().quit()

    def openFolderDialog(self):
        self.filepath,_ = QFileDialog.getOpenFileName(self, "选择图片")
        # if File_path:
        #     # 将文件夹路径记录下来，例如存储到一个实例变量中
        #     self.filepath=File_path
        #     print("选择的文件路径：", self.filepath)
        # else:
        #     print("用户取消了文件选择。",self.filepath)
    def comfirm(self):
        print("file path is",self.filepath)
        if  self.filepath=="null" or self.filepath=="":
            print("图像不存在")
        else:
            print("图像正在识别中")
            # 调用模型识别图像
            print("识别结束")
            self.textBrowser.setText(self.ship_name)
            self.textBrowser_2.setText(self.ship_type)
    def destory_filepath(self):
        self.filepath="null"
        self.textBrowser.setText("")
        self.textBrowser_2.setText("")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "选择图片"))
        self.pushButton_2.setText(_translate("MainWindow", "确认"))
        self.pushButton_3.setText(_translate("MainWindow", "撤销"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "Ship Name"))
        self.label_2.setText(_translate("MainWindow", "Ship Type"))
if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())