# -*- coding: utf-8 -*-
import pymysql
# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import Qt
from regist import *

import sys
import data_operations as db

from login import Login_Ui

if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

    app = QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    w = Login_Ui()
    w.setupUi(widget)
    widget.show()
    sys.exit(app.exec())