# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_img(object):
    def setupUi(self, Warning):
        Warning.setObjectName("Warning")
        Warning.resize(329, 140)
#         Warning.setStyleSheet("QWidget#Warning{\n"
# "background-color: rgb(207, 207, 0)\n"
# "}\n"
# "")
        self.label = QtWidgets.QLabel(Warning)
        self.label.setGeometry(QtCore.QRect(80, 40, 171, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Warning)
        self.pushButton.setGeometry(QtCore.QRect(230, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Warning)
        QtCore.QMetaObject.connectSlotsByName(Warning)

    def retranslateUi(self, Warning):
        _translate = QtCore.QCoreApplication.translate
        Warning.setWindowTitle(_translate("Warning", "Warning"))
        self.label.setText(_translate("Warning", "图片不存在"))
        self.pushButton.setText(_translate("Warning", "Cancel"))

